---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ubuntu
    box: ubuntu/bionic64
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        jdk_distr_type: local
        jdk_distr_name: jdk-11.0.10_linux-x64_bin.tar.gz
        jdk_folder: "{{ jdk_distr_name.split('-')[:2] | join('-')  }}"
        java_home: "/opt/jdk/{{ jdk_folder }}"
        environ_type: "vagrant"
verifier:
  name: ansible

